# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KnightYu'Blog # ex. I m Chuan
name: KnightYu # ex. DONGChuan
github_url: https://github.com/KnightYu # ex. https://github.com/DONGChuan
description: the world is colorful
encoding: "utf-8"

favicon: favicon.png # Image must be in assets/images
repository: https://github.com/KnightYu/KnightYu.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io


## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot
    label: Spring-Boot

  -
    href: /spring-cloud
    label: Spring-Cloud

  -
    href: /blog
    label: Archives

  -
    href: /link
    label: Link

  -
    href: /about
    label: About


# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 学习资源

  -
    href: https://wx.xiaomiquan.com/mweb/views/joingroup/join_group.html?group_id=881415141512&secret=gg9ch1oco389vka95d6zb18a8x5x804n&user_id=51122215822184
    name: 知识星球

  -
    href: /life
    name: 生活故事

  -
    href: /arch
    name: 架构之路
    
  -
    href: /jvm
    name: Jvm

  -
    href: /open-source
    name: Open-Source   

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: KnightYu
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: KnightYu
    repo: blog-comments
    oauth:
        client_id: 6dad85afb0a892b5f0cb
        client_secret: 2d25a35d3e2ee9e24535f41f77e9b80ef920ea32
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: KnightYu
    repo: blog-comments
    clientID: 6dad85afb0a892b5f0cb
    clientSecret: 2d25a35d3e2ee9e24535f41f77e9b80ef920ea32
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false